### ISSUE TITLE
test

### ISSUE THREAD

**Issue by relovesnoopy** [relovesnoopy/hello-world#1]
```yml
service: test-sqs-lambda
frameworkVersion: "3"

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.11
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        - arn:aws:sqs:ap-northeast-1:836632024539:test-sqs-lambda-queue
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource:
        - arn:aws:sqs:ap-northeast-1:836632024539:*

functions:
  hello:
    handler: handler.hello
    events:
      - sqs:
          arn: arn:aws:sqs:ap-northeast-1:836632024539:test-sqs-lambda-queue

#resources:
resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs-lambda-queue
```
